AIRPORT_LIMIT_LIST = [
    "JFK",
    "LAX",
    "MIA",
    "SFO",
    "EWR",
    "ORD",
    "ATL",
    "DFW",
    "IAH",
    "BOS",
    "MCO",
    "FLL",
    "SEA",
    "CLT",
    "DEN",
    "PHL",
    "LAS",
    "HNL",
    "DTW",
    "MSP",
    "PHX",
    "LGA",
    "TPA",
    "SLC",
    "BWI",
    "AUS",
    "SAN",
    "HOU",
    "PDX",
    "MDW",
    "OAK",
    "BNA",
    "DCA",
    "STL",
    "DAL",
]
# List of large contrywide airlines to focus on, based on market share and data availability.
# AS - Alaska Airlines, AA - American Airlines, DL - Delta Air Lines,
# F9 - Frontier Airlines, B6 - JetBlue Airways, WN - Southwest Airlines, UA - United Airlines
AIRLINE_LIMIT_LIST = ["AS", "AA", "DL", "F9", "B6", "WN", "UA"]
# not considering regional airlnes, as they have different delay patterns and are not the focus of this project.
# also dissregarding US airways, as the merged with AA
# and disregrading Spirit, as their callsign NK, only apreas, starting 2015


KEEP_COLS = {
    "Year": "int64",
    "Month": "int64",
    "DayofMonth": "int64",
    "DayOfWeek": "int64",
    "FlightDate": "str",
    "Reporting_Airline": "str",
    "Tail_Number": "str",
    "Flight_Number_Reporting_Airline": "int64",
    "Origin": "str",
    "Dest": "str",
    "CRSDepTime": "int64",
    "DepTime": "float64",
    "DepDelay": "float64",
    "DepDelayMinutes": "float64",
    "CRSArrTime": "int64",
    "ArrTime": "float64",
    "ArrDelay": "float64",
    "ArrDelayMinutes": "float64",
    "Cancelled": "float64",
    "Diverted": "float64",
    "CRSElapsedTime": "float64",
    "ActualElapsedTime": "float64",
    "AirTime": "float64",
    "Distance": "float64",
    "DistanceGroup": "int64",
    "CarrierDelay": "float64",
    "WeatherDelay": "float64",
    "NASDelay": "float64",
    "SecurityDelay": "float64",
    "LateAircraftDelay": "float64",
}
